
services:
  summary-bot:
    build:
      context: .
      args:
        INSTALL_DEV: "true"
    environment:
      ENV: "development"
      DEBUGPY_LOG_DIR: "/tmp/debugpy"
      DEBUGPY_ENABLE: "true"
      DEBUGPY_WAIT: "true"
      PYDEVD_DISABLE_FILE_VALIDATION: "1"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      DEBUGPY_SERVER: 0.0.0.0
      DEBUGPY_PORT: 5678

    ports:
      - "8080:8080"    # Web service
      - "5678:5678"    # Debugpy (IDE debugger)
    #volumes:
    #  - /app-live:/app         # Optional for live development
    command: /entrypoint.sh
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "2048M"
