# fly.toml app configuration file generated on 2025-03-24T20:44:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'summary-bot-aparine'
primary_region = 'yyz'

[build]
# Add build args to toggle dev dependencies

[build.args]
  INSTALL_DEV = "true"

[env]
# Note - this overrides *even anything passed on the command line* # GOTCHA
  ENV = "development"
  DEBUGPY_ENABLE = "true"
  DEBUGPY_WAIT = "true"
  PYDEVD_DISABLE_FILE_VALIDATION = "1"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

# Optional: expose the debug port only when you're debugging
[[services]]
  # Optional debugpy service port
  internal_port = 5678
  protocol = "tcp"

  [[services.ports]]
    # Don't expose this port publicly by default
    port = 5678
    handlers = []

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    timeout = "2s"

[http_service]
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0 # TODO - change this
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
